### ISSUE TITLE
action_fail_on_inconclusive passed with just a warning annotation

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#533]
I was expecting something red, at least in one place out of the below.

```
      - name: "Publish 'Integration Test Results' check run."
        if: success() || failure()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: 'Integration Test Results'
          comment_mode: off
          report_individual_runs: true
          action_fail_on_inconclusive: true
          test_changes_limit: 0
          junit_files: outputs/junit.xml
```

<img width="938" alt="image" src="https://github.com/EnricoMi/publish-unit-test-result-action/assets/2906988/6cb3803a-6490-447a-b3d9-61b096f67b4b">

<img width="1245" alt="image" src="https://github.com/EnricoMi/publish-unit-test-result-action/assets/2906988/5fbb5a02-675d-484a-80bd-4be0e5601ba1">

<img width="1212" alt="image" src="https://github.com/EnricoMi/publish-unit-test-result-action/assets/2906988/2851fb18-af5c-447e-b474-6d0a0f91eddc">

**Comment by EnricoMi** [comment]
Well, the action itself should fail. Does it?

**Comment by TWiStErRob** [comment]
Repro should be literally the step I added wrapped in an otherwise empty workflow.

**Comment by TWiStErRob** [comment]
Misclick, see https://github.com/TWiStErRob/github-actions-test/pull/14

**Comment by EnricoMi** [comment]
The action only fails when `action_fail` is `true`. But I can see that you might want to fail the action when no files are found, but not when tests fail. So this should be decoupled.

**Comment by EnricoMi** [comment]
Fixed in #543.

**Comment by EnricoMi** [comment]
Thanks for raising this!

**Comment by TWiStErRob** [comment]
@EnricoMi Something is still not right; original repro in OP is still the same:
https://github.com/TWiStErRob/github-actions-test/actions/runs/7253712744/job/19760905448?pr=14

What do I need to add to fail when the action inputs are wrong (e.g. no files)?
What do you define as "inconclusive"?

![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/2906988/6cd1c567-47b7-40b7-ac26-3952e7efe789)

**Comment by EnricoMi** [comment]
You have to `uses: EnricoMi/publish-unit-test-result-action/composite@dd656270a0e3b61114602ace08af7959bcf9ed32`.

**Comment by TWiStErRob** [comment]
Great success, thanks! https://github.com/TWiStErRob/github-actions-test/actions/runs/7254094439/job/19762077000?pr=14#step:2:292

[I guess the reason why I couldn't try the fix the first time is just because it's not a released version.](https://github.com/EnricoMi/publish-unit-test-result-action/blob/dd656270a0e3b61114602ace08af7959bcf9ed32/action.yml#L147)

**Comment by EnricoMi** [comment]
This has been released: https://github.com/EnricoMi/publish-unit-test-result-action/releases/tag/v2.12.0
