### ISSUE TITLE
2.16.0 syntax error

### ISSUE THREAD

**Issue by redikus3q** [EnricoMi/publish-unit-test-result-action#586]
Hey!

I have a workflow set up with some basic pyhton test file that runs with pytest and generates a junit.xml file. I have been using EnricoMi for about a year now to publish results with no issues, but since the update for 2.16.0 hit, I've been running into the following error:
![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/68228923/35aa3d3f-a49e-4365-abfd-a948322b15c9)

```
/c/Users/ADF VM/AppData/Local/Programs/Python/Python310/python3
Python that creates venv: C:\Users\ADF VM\AppData\Local\Programs\Python\Python310\python3.exe
C:\Users\ADF: line 1: syntax error near unexpected token `('
C:\Users\ADF: line 1: `[26B8:26C8][2023-06-15T14:09:00]i001: Burn v3.10.4.4718, Windows v10.0 (Build 22621: Service Pack 0), path: C:\Windows\Temp\{92DCA7E6-3972-44A9-AE81-C061C4779222}\.cr\VC_redist.x[64](https://github.com/adfdesktop/launch-autotests/actions/runs/8376472318/job/22936250951#step:2:66).exe'
  Error: Process completed with exit code 2.
```

The issue can be solved by manually setting the version of the action to the previous one, however it'd probably be best to keep using the latest one.
```yaml
uses: EnricoMi/publish-unit-test-result-action/windows/bash@v2.15.1
```

I'm running Python 3.10.9 on a self-hosted runner with Windows 11, not sure what other info to provide. My yaml is below. Thanks!

```yaml
name: TESTS
on:
  workflow_dispatch:
permissions: write-all
jobs:
  drive-tests:
    runs-on: [self-hosted, drive-image-tests]
    timeout-minutes: 1440
    steps:
      - name: Run tests
        shell: powershell
        run: |
          cd 'D:/tests'
          pytest .\test.py -s --tb=no --junitxml=junit.xml
          
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action/windows/bash@v2
        if: always()
        with:
          files: |
            D:/tests/junit.xml
```

**Comment by kvasyliev32** [comment]
Hi all. I have the similar issue. Downgrading the version helped me too
![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/153422524/15534e27-6488-4897-831a-c22cbd4934c6)

**Comment by EnricoMi** [comment]
Thanks for reporting, issue found, fix is #587.

**Comment by EnricoMi** [comment]
Fix release is imminent.

**Comment by EnricoMi** [comment]
Fix released.

**Comment by matteo-savore-deltatre** [comment]
Hi everyone, on my self hosted still not norking, what i can do ?
![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/1515441/a7669244-a16d-4b3a-a969-0f394d5f4a54)

**Comment by EnricoMi** [comment]
I have created a new issue to track this: #602
